sudo: required
dist: trusty
language: node_js
cache: yarn
branches:
  only:
  - master
node_js:
  - stable
script:
  - openssl aes-256-cbc -K $ENC_KEY -iv $ENC_IV -in .deploy/gae.json.enc -out .deploy/gae.json -d
deploy:
  provider: gae
  keyfile: .deploy/gae.json
  project: ensplorer
